// NEO FRONTIER — self-contained vanilla JS arcade engine
const $=s=>document.querySelector(s);const playfield=$("#playfield"),player=$("#player");
const scoreEl=$("#score"),highEl=$("#highScore"),levelEl=$("#level"),starsEl=$("#starsCount"),hpEl=$("#healthBar"),hpText=$("#healthText");
const startScreen=$("#startScreen"),levelClear=$("#levelClear"),upgradeScreen=$("#upgradeScreen"),pauseScreen=$("#pauseScreen"),gameOver=$("#gameOver");
const upgradeGrid=$("#upgradeGrid"),upgradeStars=$("#upgradeStars"),nextLevelEl=$("#nextLevel"),clearedLevelEl=$("#clearedLevel"),clearScore=$("#clearScore"),clearStars=$("#clearStars"),finalScore=$("#finalScore"),finalHigh=$("#finalHigh"),powerStatus=$("#powerStatus"),toast=$("#toast");
let W=0,H=0,running=false,paused=false,state="start",last=0,raf=0;
let score=0,high=Number(localStorage.getItem("neoFrontierHighScore")||0),level=1,stars=0,health=100,levelTarget=300;
let playerX=0,playerY=0,playerVX=0,playerVY=0,playerTilt=0,fireReady=0,spawnTimer=0,enemyShotTimer=0,levelTimer=0;
let bullets=[],enemies=[],enemyShots=[],powers=[],pickups=[];let keys={};let touch={left:false,right:false,up:false,down:false,shoot:false};
let powersActive={rapid:0,shield:0,double:0,pierce:0,triple:0};
let upgrades={laser:0,missile:0,shield:0,bomb:0,health:0,magnet:0};
const U={laser:{name:"LASER ARRAY",desc:"Raises direct laser damage. Cannons become hotter and brighter.",costs:[10,18,30,48,72,105]},missile:{name:"MISSILE RACK",desc:"Adds autonomous micro-missiles and increases their blast damage.",costs:[14,24,40,62,90,125]},shield:{name:"ENERGY SHIELD",desc:"Adds a stronger emergency shield buffer when Shield power-ups are active.",costs:[16,28,45,70,100,140]},bomb:{name:"MEGA BOMB",desc:"Increases B-key bomb damage and makes the panic button more decisive.",costs:[20,34,55,82,115,155]},health:{name:"HULL REPAIR",desc:"Restores 20% hull integrity immediately. Also slightly improves maximum hull.",costs:[12,22,36,55,78,108]},magnet:{name:"STAR MAGNET",desc:"Pulls stars toward the ship from farther away and accelerates collection.",costs:[9,17,29,45,66,92]}};
const audio={ctx:null};
function sound(type){try{audio.ctx||=(new(window.AudioContext||window.webkitAudioContext)());const c=audio.ctx,n=c.currentTime;if(type==="shoot"){let o=c.createOscillator(),g=c.createGain();o.type="sawtooth";o.frequency.setValueAtTime(780,n);o.frequency.exponentialRampToValueAtTime(170,n+.065);g.gain.setValueAtTime(.03,n);g.gain.exponentialRampToValueAtTime(.001,n+.075);o.connect(g).connect(c.destination);o.start();o.stop(n+.08)}else if(type==="boom"){let o=c.createOscillator(),g=c.createGain();o.type="square";o.frequency.setValueAtTime(135,n);o.frequency.exponentialRampToValueAtTime(36,n+.2);g.gain.setValueAtTime(.07,n);g.gain.exponentialRampToValueAtTime(.001,n+.22);o.connect(g).connect(c.destination);o.start();o.stop(n+.23)}else if(type==="power"){[0,.07,.14].forEach((d,i)=>{let o=c.createOscillator(),g=c.createGain();o.type="triangle";o.frequency.value=430+i*190;g.gain.setValueAtTime(.035,n+d);g.gain.exponentialRampToValueAtTime(.001,n+d+.12);o.connect(g).connect(c.destination);o.start(n+d);o.stop(n+d+.13)})}else{let o=c.createOscillator(),g=c.createGain();o.type="sawtooth";o.frequency.setValueAtTime(96,n);o.frequency.exponentialRampToValueAtTime(40,n+.5);g.gain.setValueAtTime(.065,n);g.gain.exponentialRampToValueAtTime(.001,n+.5);o.connect(g).connect(c.destination);o.start();o.stop(n+.5)}}catch(e){}}
function guitarRiff(){try{audio.ctx||=(new(window.AudioContext||window.webkitAudioContext)());const c=audio.ctx,n=c.currentTime,notes=[110,146.83,164.81,220,164.81,146.83,123.47,98];notes.forEach((f,i)=>{let o=c.createOscillator(),g=c.createGain();o.type="sawtooth";o.frequency.value=f;g.gain.setValueAtTime(.03,n+i*.07);g.gain.exponentialRampToValueAtTime(.001,n+i*.07+.06);o.connect(g).connect(c.destination);o.start(n+i*.07);o.stop(n+i*.07+.065)})}catch(e){}}
function resize(){W=playfield.clientWidth;H=playfield.clientHeight;if(!playerX)playerX=W/2;if(!playerY)playerY=H-120;playerX=Math.max(46,Math.min(W-46,playerX));playerY=Math.max(85,Math.min(H-110,playerY));player.style.left=playerX-41+"px";player.style.top=playerY+"px"}addEventListener("resize",resize);resize();
function fmt(n){return Math.max(0,Math.floor(n)).toLocaleString("en-US")}function updateHUD(){scoreEl.textContent=fmt(score);highEl.textContent=fmt(high);levelEl.textContent=level;starsEl.textContent=fmt(stars);hpEl.style.width=health+"%";hpText.textContent=Math.round(health)+"%";upgradeStars.textContent=fmt(stars)}
function makeEl(cls,parent=playfield){const e=document.createElement("div");e.className=cls;parent.appendChild(e);return e}function rect(o){return{x:o.x,y:o.y,w:o.w,h:o.h}}function hit(a,b){return a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y}
function burst(x,y,n=18){for(let i=0;i<n;i++){let e=makeEl("particle");e.style.left=x+"px";e.style.top=y+"px";e.style.setProperty("--dx",(Math.random()*150-75)+"px");e.style.setProperty("--dy",(Math.random()*150-75)+"px");setTimeout(()=>e.remove(),650)}}
function floatText(x,y,t){let e=makeEl("float-text");e.style.left=x+"px";e.style.top=y+"px";e.textContent=t;setTimeout(()=>e.remove(),760)}
function notify(t){toast.textContent=t;toast.classList.remove("show");void toast.offsetWidth;toast.classList.add("show")}
function clearObjects(){[...bullets,...enemies,...enemyShots,...powers,...pickups].forEach(o=>o.el?.remove());bullets=[];enemies=[];enemyShots=[];powers=[];pickups=[]}
function resetRun(){clearObjects();score=0;level=1;stars=0;health=100;levelTarget=300;powersActive={rapid:0,shield:0,double:0,pierce:0,triple:0};upgrades={laser:0,missile:0,shield:0,bomb:0,health:0,magnet:0};spawnTimer=0;enemyShotTimer=0;levelTimer=0;playerVX=0;playerVY=0;playerTilt=0;playerX=W/2;playerY=H-120;updateHUD();renderUpgradeCards()}
function startGame(){resetRun();running=true;paused=false;state="play";startScreen.classList.add("hidden");levelClear.classList.add("hidden");upgradeScreen.classList.add("hidden");pauseScreen.classList.add("hidden");gameOver.classList.add("hidden");guitarRiff();last=performance.now();raf=requestAnimationFrame(loop);notify("LEVEL 1 // FRONTIER SECTOR")}
function endGame(){running=false;state="dead";cancelAnimationFrame(raf);finalScore.textContent=fmt(score);finalHigh.textContent=fmt(high);gameOver.classList.remove("hidden");sound("over")}
function levelThreshold(l){return 420+l*155}
function beginLevel(l){level=l;levelTarget=score+levelThreshold(level);spawnTimer=0;enemyShotTimer=1000;state="play";levelClear.classList.add("hidden");upgradeScreen.classList.add("hidden");updateHUD();guitarRiff();notify("SECTOR "+String(level).padStart(2,"0"));last=performance.now();raf=requestAnimationFrame(loop)}
function finishLevel(){if(!running||state!=="play")return;state="clear";cancelAnimationFrame(raf);clearObjects();clearedLevelEl.textContent=level;clearScore.textContent=fmt(score);clearStars.textContent=fmt(stars);levelClear.classList.remove("hidden");updateHUD();sound("power")}
function openUpgrade(){levelClear.classList.add("hidden");upgradeScreen.classList.remove("hidden");renderUpgradeCards();nextLevelEl.textContent=level+1;state="upgrade"}
function buy(type){let u=U[type],lvl=upgrades[type],cost=u.costs[lvl]??Infinity;if(lvl>=u.costs.length||stars<cost)return false;stars-=cost;upgrades[type]++;if(type==="health")health=Math.min(100+upgrades.health*5,health+20);updateHUD();renderUpgradeCards();sound("power");notify(u.name+" // INSTALLED");return true}
function renderUpgradeCards(){upgradeGrid.innerHTML="";Object.keys(U).forEach(type=>{let u=U[type],lvl=upgrades[type],cost=u.costs[lvl]??Infinity;let card=document.createElement("div");card.className="upgrade-card";card.innerHTML=`<h3>${u.name}</h3><p>${u.desc}</p><div class="upgrade-level">LEVEL ${lvl}/${u.costs.length}</div><button class="upgrade-btn" ${lvl>=u.costs.length||stars<cost?"disabled":""}>SPEND ◆ ${cost}</button>`;card.querySelector("button").onclick=()=>buy(type);upgradeGrid.appendChild(card)})}
function deployNext(){upgradeScreen.classList.add("hidden");beginLevel(level+1)}
function togglePause(){if(!running||state!=="play")return;paused=!paused;if(paused){state="paused";pauseScreen.classList.remove("hidden");cancelAnimationFrame(raf)}else{state="play";pauseScreen.classList.add("hidden");last=performance.now();raf=requestAnimationFrame(loop)}}
function powerDuration(type){return type==="rapid"?9000:10000}
function shoot(){if(!running||state!=="play"||performance.now()<fireReady)return;let rapid=powersActive.rapid>0;fireReady=performance.now()-(rapid?10:0)+Math.max(50,rapid?65:95);let count=powersActive.triple>0?3:1,offs=count===3?[-20,0,20]:[0];offs.forEach(off=>{let e=makeEl("bullet"+(powersActive.pierce>0?" pierce":""));let x=playerX-3+off,y=playerY+8;e.style.left=x+"px";e.style.top=y+"px";bullets.push({el:e,x,y,w:7,h:22,vy:-780,pierce:powersActive.pierce>0,damage:16+upgrades.laser*6})});if(upgrades.missile&&Math.random()<.1+upgrades.missile*.035){let e=makeEl("missile");let x=playerX-4,y=playerY+8;e.style.left=x+"px";e.style.top=y+"px";bullets.push({el:e,x,y,w:8,h:20,vy:-500,missile:true,damage:32+upgrades.missile*10})}sound("shoot")}
function enemySpec(type){let d={scout:{w:58,h:44,hp:32+level*3,speed:48+level*2.0,drift:58,fire:2550},tank:{w:72,h:54,hp:78+level*8,speed:30+level*1.5,drift:28,fire:2200},elite:{w:66,h:58,hp:120+level*12,speed:68+level*3.0,drift:85,fire:1900},striker:{w:52,h:62,hp:48+level*5,speed:92+level*4,drift:105,fire:2200}}[type];return d}
function chooseEnemy(){let r=Math.random(),elite=Math.min(.05+level*.018,.2),tank=Math.min(.09+level*.015,.24),striker=Math.min(.08+level*.014,.2);if(r<elite)return"elite";if(r<elite+tank)return"tank";if(r<elite+tank+striker)return"striker";return"scout"}
function spawnEnemy(){let type=chooseEnemy(),d=enemySpec(type),e=makeEl("enemy "+type);e.style.left=(20+Math.random()*(W-d.w-40))+"px";e.style.top="-80px";e.innerHTML='<div class="enemy-hp"><i></i><b>100%</b></div><div class="enemy-body"><div class="enemy-fin"></div></div>';let x=parseFloat(e.style.left);enemies.push({el:e,x,y:-80,w:d.w,h:d.h,hp:d.hp,max:d.hp,vy:d.speed,type,phase:Math.random()*Math.PI*2,amp:d.drift,turn:Math.random()*1.5+0.7,nextShot:d.fire*(.7+Math.random()*.5)})}
function enemyShoot(en){if(en.y<0)return;let e=makeEl("enemy-shot"+(en.type==="elite"?" ion":""));let x=en.x+en.w/2-3,y=en.y+en.h-1;e.style.left=x+"px";e.style.top=y+"px";let tx=playerX-x,ty=(H-120)-y,len=Math.hypot(tx,ty)||1;let base=level>=7?205+level*7:145+level*5;enemyShots.push({el:e,x,y,w:8,h:20,vx:tx/len*base,vy:ty/len*base,dmg:en.type==="tank"?16:12})}
function damageEnemy(en,dmg){if(en.dead)return;en.hp-=dmg;let p=Math.max(0,en.hp/en.max*100);en.el.querySelector("i").style.width=p+"%";en.el.querySelector("b").textContent=Math.round(p)+"%";if(en.hp<=0){en.dead=true;let base=en.type==="tank"?45:en.type==="elite"?85:en.type==="striker"?30:25;let gain=Math.round(base*(powersActive.double>0?2:1));score+=gain;burst(en.x+en.w/2,en.y+en.h/2,en.type==="elite"?27:16);floatText(en.x,en.y,"+"+gain);sound("boom");if(Math.random()<.17)spawnPower(en.x+15,en.y+10);if(Math.random()<.34)spawnStar(en.x+20,en.y+16);en.el.remove();updateHigh()}}
function spawnPower(x,y){let types=["rapid","shield","double","pierce","triple"],type=types[Math.floor(Math.random()*types.length)],e=makeEl("power "+type);e.textContent={rapid:"R",shield:"S",double:"2X",pierce:"P",triple:"3"}[type];e.style.left=x+"px";e.style.top=y+"px";powers.push({el:e,x,y,w:30,h:30,vy:105,type})}
function spawnStar(x,y){let e=makeEl("star");e.style.left=x+"px";e.style.top=y+"px";pickups.push({el:e,x,y,w:13,h:13,vy:88})}
function collectPower(p){powersActive[p.type]=powerDuration(p.type);p.el.remove();p.dead=true;sound("power");notify(p.type.toUpperCase()+" ONLINE")}
function collectStar(s){stars++;s.el.remove();s.dead=true;updateHUD();sound("power");floatText(s.x,s.y,"◆ +1")}
function takeHit(amount){if(powersActive.shield>0){powersActive.shield=Math.max(0,powersActive.shield-1400);notify("SHIELD ABSORBED HIT");return}health=Math.max(0,health-amount);updateHUD();playerTilt+=(Math.random()<.5?-1:1)*8;playerVX*=.45;burst(playerX,playerY+35,6);if(health<=0)endGame()}
function updateHigh(){if(score>high){high=score;localStorage.setItem("neoFrontierHighScore",high)}updateHUD()}
function updatePowerUI(){let names=[];Object.entries(powersActive).forEach(([k,v])=>{if(v>0)names.push(k.toUpperCase()+" "+(v/1000).toFixed(1)+"s")});powerStatus.textContent=names.join("   •   ")}
function loop(t){if(!running||state!=="play")return;raf=requestAnimationFrame(loop);let dt=Math.min(.032,((t-last)||16)/1000);last=t;
  if(score>=levelTarget){finishLevel();return}
  // Difficulty ramps gently. Early sectors breathe; later sectors become dense, faster and more accurate.
  const spawnRate=Math.max(650,1850-level*42);spawnTimer-=dt*1000;if(spawnTimer<=0){spawnTimer=spawnRate;spawnEnemy();if(level>=6&&Math.random()<Math.min(.12,(level-5)*.025))spawnEnemy()}
  enemyShotTimer-=dt*1000;if(enemyShotTimer<=0){enemyShotTimer=Math.max(700,2300-level*45);let shooters=enemies.filter(e=>!e.dead&&e.y>0);if(shooters.length){shooters[Math.floor(Math.random()*shooters.length)].nextShot=0}}
  Object.keys(powersActive).forEach(k=>{if(powersActive[k]>0)powersActive[k]-=dt*1000});updatePowerUI();
  let dir=(keys.ArrowLeft||keys.a||touch.left?-1:0)+(keys.ArrowRight||keys.d||touch.right?1:0);let vdir=(keys.ArrowUp||keys.w||touch.up?-1:0)+(keys.ArrowDown||keys.s||touch.down?1:0);let accel=2200,drag=dir?0.9:0.84,vaccel=1450,vdrag=vdir?0.9:0.86;playerVX+=dir*accel*dt;playerVX*=drag;playerVX=Math.max(-620,Math.min(620,playerVX));playerX+=playerVX*dt;playerX=Math.max(46,Math.min(W-46,playerX));playerVY+=vdir*vaccel*dt;playerVY*=vdrag;playerVY=Math.max(-300,Math.min(300,playerVY));playerY+=playerVY*dt;playerY=Math.max(82,Math.min(H-105,playerY));let targetTilt=Math.max(-25,Math.min(25,playerVX/22));playerTilt+=(targetTilt-playerTilt)*Math.min(1,dt*9);player.style.left=(playerX-41)+"px";player.style.top=playerY+"px";player.style.transform=`rotate(${playerTilt}deg) translateY(${Math.sin(t/100)*1.5}px)`;
  if(keys[" "]||touch.shoot)shoot();
  if(powersActive.shield>0&&!player.querySelector(".shield-ring")){let s=document.createElement("div");s.className="shield-ring";player.appendChild(s)}else if(powersActive.shield<=0)player.querySelector(".shield-ring")?.remove();
  bullets.forEach(b=>{b.x+=b.vx||0;b.y+=b.vy*dt;b.el.style.left=b.x+"px";b.el.style.top=b.y+"px"});
  enemies.forEach(en=>{en.y+=en.vy*dt;en.x+=Math.sin(t/700*en.turn+en.phase)*en.amp*dt;en.x+=(Math.sin(t/1300+en.phase)*8*dt);en.x=Math.max(8,Math.min(W-en.w-8,en.x));en.el.style.left=en.x+"px";en.el.style.top=en.y+"px";en.nextShot-=dt*1000;if(en.nextShot<=0){en.nextShot=(enemySpec(en.type).fire*(.7+Math.random()*.6))/Math.min(1.7,1+level*.04);enemyShoot(en)}for(const b of bullets){if(!b.dead&&!en.dead&&hit(rect(b),rect(en))){damageEnemy(en,b.damage);if(b.missile){b.dead=true;burst(b.x,b.y,10)}else if(!b.pierce)b.dead=true}}if(!en.dead&&hit(rect(en),{x:playerX-34,y:playerY-2,w:68,h:68})){en.dead=true;en.el.remove();takeHit(en.type==="tank"?23:en.type==="elite"?28:17)}});
  enemyShots.forEach(s=>{s.x+=s.vx*dt;s.y+=s.vy*dt;s.el.style.left=s.x+"px";s.el.style.top=s.y+"px";if(!s.dead&&hit(rect(s),{x:playerX-29,y:playerY+4,w:58,h:60})){s.dead=true;s.el.remove();burst(s.x,s.y,8);takeHit(s.dmg)}else if(s.y>H+30||s.x<-40||s.x>W+40){s.dead=true;s.el.remove()}});
  powers.forEach(p=>{p.y+=p.vy*dt;p.el.style.top=p.y+"px";if(hit(rect(p),{x:playerX-31,y:playerY+2,w:62,h:64}))collectPower(p);else if(p.y>H+40){p.dead=true;p.el.remove()}});
  pickups.forEach(s=>{let dx=playerX-(s.x+7),dy=(playerY+20)-(s.y+7),dist=Math.hypot(dx,dy),range=60+upgrades.magnet*40;if(dist<range){let pull=2.5+upgrades.magnet*.75;s.x+=dx*pull*dt;s.y+=dy*pull*dt}s.y+=s.vy*dt;s.el.style.left=s.x+"px";s.el.style.top=s.y+"px";if(hit(rect(s),{x:playerX-31,y:playerY+2,w:62,h:64}))collectStar(s);else if(s.y>H+40){s.dead=true;s.el.remove()}});
  bullets=bullets.filter(b=>{if(b.dead||b.y<-40){b.el.remove();return false}return true});enemies=enemies.filter(e=>!e.dead);enemyShots=enemyShots.filter(s=>!s.dead);powers=powers.filter(p=>!p.dead);pickups=pickups.filter(s=>!s.dead);updateHUD();
}
function megaBomb(){if(!running||state!=="play"||stars<50)return;stars-=50;let power=240+upgrades.bomb*90;enemies.slice().forEach(en=>damageEnemy(en,power));burst(playerX,playerY+25,36);notify("MEGA BOMB // DETONATED");updateHUD()}
$("#startBtn").onclick=startGame;$("#restartBtn").onclick=startGame;$("#pauseBtn").onclick=togglePause;$("#resumeBtn").onclick=togglePause;$("#openUpgradeBtn").onclick=openUpgrade;$("#continueBtn").onclick=deployNext;
addEventListener("keydown",e=>{if(["ArrowLeft","ArrowRight"," "].includes(e.key))e.preventDefault();keys[e.key]=true;if(e.key.toLowerCase()==="p"&&!e.repeat)togglePause();if(e.key.toLowerCase()==="b"&&!e.repeat)megaBomb()});addEventListener("keyup",e=>keys[e.key]=false);
function bindTouch(id,key){let b=$(id);["pointerdown","pointerenter"].forEach(ev=>b.addEventListener(ev,e=>{if(e.buttons||ev==="pointerdown"){e.preventDefault();touch[key]=true}}));["pointerup","pointerleave","pointercancel"].forEach(ev=>b.addEventListener(ev,e=>{e.preventDefault();touch[key]=false}))}bindTouch("#leftTouch","left");bindTouch("#rightTouch","right");bindTouch("#upTouch","up");bindTouch("#downTouch","down");bindTouch("#shootTouch","shoot");
updateHUD();renderUpgradeCards();
// Generate layered, animated stars without external assets.
(function makeStars(){let frag=document.createDocumentFragment();for(let i=0;i<460;i++){let s=document.createElement("span");s.className="space-dust";s.style.left=Math.random()*100+"vw";s.style.top=Math.random()*100+"vh";s.style.opacity=(.25+Math.random()*.75).toFixed(2);s.style.transform=`scale(${.35+Math.random()*2.4})`;s.style.animation=`starFloat ${10+Math.random()*28}s linear ${-Math.random()*28}s infinite`;if(Math.random()<.08)s.style.boxShadow="0 0 9px #fff,0 0 24px rgba(235,240,245,.8)";frag.appendChild(s)}$("#spaceBackdrop").appendChild(frag)})()
